### ISSUE TITLE
如果脚本运行正常，运行结果是什么样的？

### ISSUE THREAD

**Issue by yburger** [TestSmirk/oracleLogin#2]
第一次运行报错，装了一个依赖包以后运行`node oracle.js`不再报错了，可是没有输出任何结果，这样算运行成功了吗?
![Screenshot_2019-10-19-20-26-54-517_com sonelli juicessh](https://user-images.githubusercontent.com/11057647/67144910-e3b48280-f2ae-11e9-8d4a-3a688152c107.jpg)

**Comment by TestSmirk** [comment]
对。没报错就成功了

**Comment by reidmex** [comment]
建议修改一下js脚本，成功后打印输出，然后退出js，否则以为脚本挂死了

**Comment by TestSmirk** [comment]
已加入执行日志.

**Comment by reidmex** [comment]
@TestSmirk

这样就是登录console成功了？

等待页面加载 https://console.ap-mumbai-1.oraclecloud.com
输入tenant
点击确定
等待下一页加载
输入用户名
输入密码
点击登陆
successSat Oct 19 2019 09:49:34 GMT-0400 (Eastern Daylight Time)
