### ISSUE TITLE
没有对登录结果进行检查，登录失败仍然打印success

### ISSUE THREAD

**Issue by reidmex** [TestSmirk/oracleLogin#3]
console地址填错，或者用户或者密码错误，都不会报错，最后直接来个success。。。

   await page.click("body > div.main-container > div.right-panel > table > tbody > tr:nth-child(3) > td:nth-child(3) > form > div:nth-child(14) > input[type=submit]");
    console.log("success"+new Date());

**Comment by TestSmirk** [comment]
好吧，我加个判断

**Comment by reidmex** [comment]
> 好吧，我加个判断

大佬，啥时候完善一下这个脚本？

**Comment by TestSmirk** [comment]
最近在忙. 这两天改下吧...

**Comment by reidmex** [comment]
最后那个判断不起作用，即使填个错误的密码，仍然打印登录成功。@TestSmirk

**Comment by TestSmirk** [comment]
不会吧,我这就是失败啊,  
![image](https://user-images.githubusercontent.com/12248888/67731082-f6a71f80-fa31-11e9-8762-ca79a96fea33.png)

---  

> 最后那个判断不起作用，即使填个错误的密码，仍然打印登录成功。@TestSmirk
